// wc/audioplayer/src/main.ts
import { createCustomElement } from '@angular/elements';
import { createApplication } from '@angular/platform-browser';
import { importProvidersFrom } from '@angular/core';
import { AudioPlayerComponent } from './app/app.component';

import { CommonModule } from '@angular/common';

export async function createAudioPlayerElement() {
  const app = await createApplication({
    providers: [
      importProvidersFrom(CommonModule),
    ]
  });

  const audioPlayerElement = createCustomElement(AudioPlayerComponent, {
    injector: app.injector
  });

  customElements.define('ladon-audioplayer', audioPlayerElement);

  return audioPlayerElement;
}

export function defineAudioPlayerElement() {
  if (!customElements.get('ladon-audioplayer')) {
    createAudioPlayerElement();
  }
}

defineAudioPlayerElement();

// wc/pdfviewer/src/main.ts
import { createApplication} from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { PdfviewerComponent } from './app/pdfviewer.component';
import {createCustomElement} from "@angular/elements";


export async function createPdfViewerElement() {
  const app = await createApplication(appConfig);

  const pdfViewerElement = createCustomElement(PdfviewerComponent, {
    injector: app.injector
  });

  customElements.define('ladon-pdfviewer', pdfViewerElement);

  return pdfViewerElement;
}

export function definePdfViewerElement() {
  if (!customElements.get('ladon-pdfviewer')) {
    createPdfViewerElement();
  }
}

definePdfViewerElement();
