// wc/imageeditor/src/main.ts
import { createCustomElement } from '@angular/elements';
import { createApplication } from '@angular/platform-browser';
import { importProvidersFrom } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ImageEditorComponent } from './app/app.component';

export async function createImageEditorElement() {
  const app = await createApplication({
    providers: [importProvidersFrom(CommonModule)],
  });

  const imageEditorElement = createCustomElement(ImageEditorComponent, {
    injector: app.injector,
  });

  customElements.define('ladon-image-editor', imageEditorElement);

  return imageEditorElement;
}

export function defineImageEditorElement() {
  if (!customElements.get('ladon-image-editor')) {
    createImageEditorElement();
  }
}

defineImageEditorElement();

// wc/pdfviewer/src/main.ts
import { createApplication} from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { PdfviewerComponent } from './app/pdfviewer.component';
import {createCustomElement} from "@angular/elements";


export async function createPdfViewerElement() {
  const app = await createApplication(appConfig);

  const pdfViewerElement = createCustomElement(PdfviewerComponent, {
    injector: app.injector
  });

  customElements.define('ladon-pdfviewer', pdfViewerElement);

  return pdfViewerElement;
}

export function definePdfViewerElement() {
  if (!customElements.get('ladon-pdfviewer')) {
    createPdfViewerElement();
  }
}

definePdfViewerElement();
